"""add user id to tests

Revision ID: 3828969e6c44
Revises: 53a51aae539d
Create Date: 2024-04-07 23:40:09.855456

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3828969e6c44"
down_revision = "53a51aae539d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "biological_test", sa.Column("user_id", sa.UUID(as_uuid=False), nullable=True)
    )
    op.create_index(
        op.f("ix_biological_test_user_id"), "biological_test", ["user_id"], unique=False
    )
    op.create_foreign_key(
        "fk_biological_test_user_id",
        "biological_test",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###

# NOTE: There was some problem with dropping the foreign key when no user has taken a test, might need to comment the line out on downgrade in that case, and uncomment again.

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_biological_test_user_id", "biological_test", type_="foreignkey"
    )
    op.drop_index(op.f("ix_biological_test_user_id"), table_name="biological_test")
    op.drop_column("biological_test", "user_id")
    # ### end Alembic commands ###
